name: upscale
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.13
  - pip
  - numpy
  - imageio
  - natsort
  - tqdm
  - libwebp
  - rich
  - pillow
  - unidecode
  - requests
  - pytest
  - pip:
    - opencv-python
    - spandrel
    - torch
    - torchvision
    - torchaudio
    - --index-url https://download.pytorch.org/whl/cu126
    - --extra-index-url https://pypi.org/simple