name: upscale
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - pytorch-cuda=11.8
  - conda-forge::libwebp
  - conda-forge::opencv
  - pip:
    - rich
    - unidecode
    - pillow
    - natsort
    - imageio
    - basicsr>=1.4.2
    - facexlib>=0.2.5
    - gfpgan>=1.3.5
    - tqdm
