name: upscale
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch=2.0.*
  - torchvision
  - torchaudio
  - numpy
  - pytorch-cuda=11.8
  - imageio
  - natsort
  - tqdm
  - facexlib>=0.2.5
  - libwebp
  - rich
  - pillow
  - unidecode
  - conda-forge::opencv
  - pip:
    - basicsr>=1.4.2
    - gfpgan>=1.3.5
    - tqdm
    - opencv-contrib-python
