name: upscale
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.13
  - pip
  - numpy
  - conda-forge::pytorch-gpu~=2.6.0
  - imageio
  - natsort
  - tqdm
  - libwebp
  - rich
  - pillow
  - unidecode
  - requests
  - pytest
  - pip:
    - opencv-python
    - spandrel
