name: upscale
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - imageio
  - natsort
  - tqdm
  - libwebp
  - rich
  - pillow
  - unidecode
  - requests
  - conda-forge::opencv
  - pytest
  - pip:
    - opencv-contrib-python
    - spandrel
