name: Docker Image CI

on:
  workflow_dispatch:
  push:
    paths:
      - dockerfiles/
      - environment.yml
      - requirements.txt

jobs:
  build-conda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build & Push Docker Images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfiles/conda.Dockerfile
          tags: comic-upscaler:nvidia-latest,comic-upscaler:conda-nvidia-latest

  build-pip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build & Push Docker Images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfiles/pip.Dockerfile
          tags: comic-upscaler:pip-latest